# Generated by Django 3.0.3 on 2020-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X1', models.FloatField(default=0.0)),
                ('X2', models.FloatField(default=0.0)),
                ('X3', models.FloatField(default=0.0)),
            ],
        ),
    ]
