# Generated by Django 3.0.3 on 2020-04-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samples',
            new_name='Sample',
        ),
    ]
